user_pref("media.peerconnection.enabled", false);
user_pref("media.peerconnection.turn.disable", true);
user_pref("media.peerconnection.use_document_iceservers", false);
user_pref("media.peerconnection.video.enabled", false);
user_pref("media.peerconnection.identity.timeout", 1);

user_pref("privacy.donottrackheader.enabled", true);
user_pref("geo.enabled", false);

user_pref("browser.pocket.enabled", false);
user_pref("browser.safebrowsing.appRepURL", "");
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.newtabpage.enhanced", false);
user_pref("webgl.disabled", true);
user_pref("browser.safebrowsing.malware.enabled", false);
user_pref("browser.fixup.alternate.enabled", false);
user_pref("extensions.getAddons.cache.enabled", false);
user_pref("datareporting.healthreport.service.enabled", false);
user_pref("loop.enabled", false);
user_pref("browser.newtabpage.enabled", false);
user_pref("network.cookie.cookieBehavior", 1);
user_pref("privacy.trackingprotection.pbmode.enabled", true);
user_pref("dom.indexedDB.enabled", false);
user_pref("network.prefetch-next", false);
user_pref("network.dns.disablePrefetch", true);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("app.update.auto", false);
user_pref("network.http.referer.spoofSource", true);
user_pref("beacon.enabled", false);
user_pref("browser.send_pings", false);
user_pref("toolkit.telemetry.enabled", false);
user_pref("privacy.trackingprotection.enabled", true);
user_pref("browser.newtab.preload", false);
user_pref("general.warnOnAboutConfig", false);
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("extensions.autoDisableScopes", 14);
user_pref("datareporting.policy.dataSubmissionEnabled", false);
user_pref("dom.battery.enabled", false);
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("privacy.donottrackheader.value", 1);
user_pref("browser.safebrowsing.enabled", false);
user_pref("browser.selfsupport.url", "");
user_pref("dom.event.clipboardevents.enabled", false);
user_pref("network.cookie.lifetimePolicy", 2);
user_pref("browser.cache.offline.enable", false);
user_pref("browser.sessionstore.max_tabs_undo", 2);

user_pref("browser.search.countryCode", "");
user_pref("browser.search.defaultenginename", "DisconnectSearch");
user_pref("browser.search.region", "");
user_pref("browser.search.suggest.enabled", false);

user_pref("browser.startup.homepage", "http://enboard.co/yoaz20/");
user_pref("browser.startup.homepage_override.mstone", "ignore");


user_pref("extensions.agentSpoof.acceptDefault", true);
user_pref("extensions.agentSpoof.acceptEncoding", true);
user_pref("extensions.agentSpoof.acceptLang", true);
user_pref("extensions.agentSpoof.acceptLangChoice", "en-US");
user_pref("extensions.agentSpoof.authorization", false);
user_pref("extensions.agentSpoof.canvas", false);
user_pref("extensions.agentSpoof.colordepth", "24");
user_pref("extensions.agentSpoof.disableRef", false);
user_pref("extensions.agentSpoof.fullWhiteList", "[{\"url\": \"addons.mozilla.org\"}]");
user_pref("extensions.agentSpoof.ifnone", false);
user_pref("extensions.agentSpoof.limitTab", false);
user_pref("extensions.agentSpoof.pixeldepth", "24");
user_pref("extensions.agentSpoof.screenSize", "random");
user_pref("extensions.agentSpoof.screens", "800x600,1024x600,1024x768,1152x864,1280x720,1280x768,1280x800,1280x960,1280x1024,1360x768,1366x768,1440x900,1400x1050,1600x900,1600x1200,1680x1050,1920x1080,1920x1200,2048x1152,2560x1440,2560x1600");
user_pref("extensions.agentSpoof.scriptInjection", true);
user_pref("extensions.agentSpoof.siteWhiteList", "addons.mozilla.org");
user_pref("extensions.agentSpoof.timeInterval", "60");
user_pref("extensions.agentSpoof.tzOffset", "default");
user_pref("extensions.agentSpoof.uaChosen", "random_0,2");
user_pref("extensions.agentSpoof.via", false);
user_pref("extensions.agentSpoof.viadd", "random");
user_pref("extensions.agentSpoof.viaip", "1.1.1.1");
user_pref("extensions.agentSpoof.whiteListAccept", "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8");
user_pref("extensions.agentSpoof.whiteListAcceptEncoding", "gzip, deflate");
user_pref("extensions.agentSpoof.whiteListAcceptLanguage", "en-US,en;q=0.5");
user_pref("extensions.agentSpoof.whiteListAppCodeName", "Mozilla");
user_pref("extensions.agentSpoof.whiteListAppName", "Netscape");
user_pref("extensions.agentSpoof.whiteListAppVersion", "5.0");
user_pref("extensions.agentSpoof.whiteListDisabled", false);
user_pref("extensions.agentSpoof.whiteListOsCpu", "Linux x86_64");
user_pref("extensions.agentSpoof.whiteListPlatform", "Linux");
user_pref("extensions.agentSpoof.whiteListUserAgent", "Mozilla/5.0 (X11; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0");
user_pref("extensions.agentSpoof.whiteListVendor", "");
user_pref("extensions.agentSpoof.whiteListVendorSub", "");
user_pref("extensions.agentSpoof.windowName", false);
user_pref("extensions.agentSpoof.xff", false);
user_pref("extensions.agentSpoof.xffdd", "random");
user_pref("extensions.agentSpoof.xffip", "1.1.1.1");